### ISSUE TITLE
Doesn't run on Windows 10

### ISSUE THREAD

**Issue by otofoto** [KrishnaSolo/iSBET#1]
Corrupt Application Name: RoadwareSBET.exe, version: 2019.7.8.1, timestamp: 0x5d4e1094
Damaged Module Name: KERNELBASE.dll, Version: 10.0.18362.628, Timestamp: 0x54734dee
Exception code: 0xe0434352
Defect Offset: 0x00113db2
Defective process ID: 0x3670
Corrupted Application Startup Time: 0x01d5e6324af49ed1
Corrupt Application Path: C: \ Temp \ iSBET-master \ RoadwareSBET \ RoadwareSBET.exe
Damaged module path: C: \ WINDOWS \ System32 \ KERNELBASE.dll

**Comment by KrishnaSolo** [comment]
Hi,
Please try the following:
https://answers.microsoft.com/en-us/windows/forum/all/applications-fail-to-start-with-kernelbasedll/44a4c2ad-a43f-479b-b026-bcdc2ff01285
Should work with an updated kernelbase.dll

**Comment by otofoto** [comment]
Same happens on Win7 it is missing some file.

`Application: RoadwareSBET.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at RoadwareSBET.Domain.frmSBETDialog.InitializeControls()
   at RoadwareSBET.Domain.frmSBETDialog..ctor()
   at RoadwareSBET.Domain.Program.Main()`

`Faulting application name: RoadwareSBET.exe, version: 2019.7.8.1, time stamp: 0x5d4e1094
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24354, time stamp: 0x5c356365
Exception code: 0xe0434352
Fault offset: 0x0000c5af
Faulting process id: 0x1b4
Faulting application start time: 0x01d5ebba1bac33ea
Faulting application path: D:\utils\sbet\RoadwareSBET\RoadwareSBET.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 597753c2-57ad-11ea-96a8-00270e0a7972`
